language: python
python:
  - "3.5"
# command to install dependencies
install:
  - pip install aiohttp
  - pip install websockets
  - sudo apt-get install libffi-dev
  - python3 -m pip install -U discord.py[voice]
# command to run tests
script: nosetests
